#!/bin/sh

RTEMS_DIR=/home/projects/movidius/m8_gui/tools/18.06.6/linux64/sparc-myriad-rtems-6.3.0

#RTEMS_GLOBAL_CFLAGS="-ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -finit-priority"

MINIGUI_CFLAGS="-I${RTEMS_DIR}/minigui/include"
MINIGUI_LIBS=libminigui_ths.a

rm -f config.cache config.status

CC=${RTEMS_DIR}/bin/sparc-myriad-rtems-gcc \
CFLAGS="-I${RTEMS_DIR}/sparc-myriad-rtems/include -I${RTEMS_DIR}/pnglib/include -I${RTEMS_DIR}/zlib/include -I${RTEMS_DIR}/pnglib/include -I${RTEMS_DIR}/minigui/include -I${RTEMS_DIR}/mgplus/include" \
LDFLAGS="-L${RTEMS_DIR}/lib/gcc/sparc-myriad-rtems/6.3.0 -L${RTEMS_DIR}/pnglib/lib -L${RTEMS_DIR}/zlib/lib -L${RTEMS_DIR}/pnglib/lib -L${RTEMS_DIR}/minigui/lib -L${RTEMS_DIR}/mgplus/lib" \
CXXFLAGS="-I${RTEMS_DIR}/sparc-myriad-rtems/include -I${RTEMS_DIR}/pnglib/include -I${RTEMS_DIR}/zlib/include -I${RTEMS_DIR}/pnglib/include -I${RTEMS_DIR}/minigui/include -L${RTEMS_DIR}/mgplus/lib" \
./configure --prefix=/home/projects/movidius/m8_gui/tools/18.06.6/linux64/sparc-myriad-rtems-6.3.0/mgutils \
    --build=i686-linux \
    --host=sparc-myriad-rtems \
    --target=sparc-myriad-rtems \
    --enable-static \
	--enable-dlgopenfile=no
